zk:
  addressList:
    - 127.0.0.1:2181
#    - 127.0.0.1:2182
#    - 127.0.0.1:2183
  connectTimeOut: 10000
  sessionTimeOut: 10000
  registryPath: "/defaultRegistry"
spring:
  profiles:
    active: slave1